export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const LIST_PRACTITIONERS = 'LIST_PRACTITIONERS';
export const SET_PRACTITIONER = 'SET_PRACTITIONER';
export const BOOKING_SLOT = 'BOOKING_SLOT';
export const DISPLAY_SLOT = 'DISPLAY_SLOT';
